### ISSUE TITLE
Döküman Eksiği

### ISSUE THREAD

**Issue by kocakmstf** [K12net/K12NET-Frame-iOS#1]
Merhaba,

Uygulamayı indiren kullanıcıların nereleri değiştireceğini, hangi ayarları yapacağını bir döküman olarak ekleyebilir misiniz?

**Comment by K12net** [comment]
Merhaba,

 

Herhangi bir ayar yapmalarına gerek yoktur. Kullanıcılar kullanıcı adı ve parola bilgilerini girerek işlem sağlayabilirler. 

 

İyi Çalışmalar

 

Emre GÜNGÖR

 

Teknik Destek / Tech Support

Tel: +90 312 299 23 13  

Mail: destek@k12net.com <mailto:destek@k12net.com> 

Atlas Eğitim Yazılımları

 

 <http://www.k12net.com/>   <https://www.facebook.com/K12NET/>    <https://www.instagram.com/k12net/>    <https://www.youtube.com/user/K12NETSIS>
